name: universitas_mdp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Regular.ttf